### PR TITLE
Auto populate the Topic EditFlashcardModal.

### LINKED ISSUE #842: Topic is not auto populated in the EditFlashcardModal form
**Describe the bug**
When clicking on a row on the flashcard table at `/admin/flashcards`, which then opens the Edit Flashcard modal, the select for `topic` is auto-defaulted to `Business Associations` and not the actual topic. The current value for `topic` should be the first value this input is set to in the `EditFlashcardModal`

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #842

### CODE REVIEW

File: packages/shared-ui/src/forms/base/select.tsx [hunk 1]
```diff
@@ -26,15 +22,19 @@ export const Select = ({
...
-        color={colors.text.light}
-      >
+      <Box color={colors.text.light}>
         <Controller
           as={ReactSelect}
           data-testid={testId}
           name={name}
           control={control}
           options={options}
+          defaultValue={{
```
Comment (nisarhassan12) [inline packages/shared-ui/src/forms/base/select.tsx:32]: @shicholas The `defaultValue` prop does not seem to be working as expected. So I have opened an issue for that here https://github.com/react-hook-form/react-hook-form/issues/2974
